// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package datebase

import (
	"github.com/google/uuid"
)

type Cake struct {
	ID          uuid.UUID
	Type        string
	LayerNumber int16
	TiereNumber int16
	Size        string
	Price       string
}

type Filling struct {
	ID    uuid.UUID
	Name  string
	Price string
}

type Flavor struct {
	ID       uuid.UUID
	Name     string
	AddPrice string
}

type Frosting struct {
	ID       uuid.UUID
	Name     string
	AddPrice string
}
